### ISSUE TITLE
writing cards

### ISSUE THREAD

**Issue by iamzhuoxuan** [iamzhuoxuan/keeptenyears#1]

**Comment by ouyangzhiping** [comment]
也许下一步，可以使用 Jekyll，将本博客变身为网站。

参考：

* [理想的写作环境：Git+Github+Markdown+Jekyll - 阳志平的网志](http://www.yangzhiping.com/tech/writing-space.html)
* [搭建一个免费的，无限流量的 Blog----github Pages 和 Jekyll 入门 - 阮一峰的网络日志](http://www.ruanyifeng.com/blog/2012/08/blogging_with_jekyll.html)
* [Jekyll • Simple, blog-aware, static sites - Transform your plain text into static websites and blogs](https://jekyllrb.com/)

**Comment by iamzhuoxuan** [comment]
被阳老翻牌了好激动！！
已经用Jekyll搭建了自己的博客，你提供的3个网站都参考过 ; )
阳老有空可以来看看 www.zhanzhuoxuan.com
